name: Deploy Discord Bot

on:
  push:
    branches: [main]  # mainブランチにpushされたときに実行

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    environment: production  # GitHubのEnvironmentsに合わせる

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: dotnet run